server:
  port: 8080
  servlet:
    context-path: /api/core

spring:
  application:
    name: pinlog-back
  security:
    user:
      name: ssafy
      password: ssafy

build:
  sha: ${BUILD_SHA:unknown}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
